/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Banco.Bd;
import Codigo.Conta;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinicius
 */
public class Contashoje extends javax.swing.JFrame {
    Date data = new Date();
    Calendar calendar = Calendar.getInstance();
        
    /**
     * Creates new form Contashoje
     */
    public Contashoje() {
        initComponents();
    }
    public void datahoje(){
        calendar.add(Calendar.DAY_OF_MONTH,+0);        
        SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
        jLabel1.setText(formatar.format(calendar.getTime()));
    }
    public void pegahoje(Date data) throws ParseException{
        Bd bd = new Bd();
        bd.getConnection();
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        ArrayList<Conta> array = new ArrayList();   
        try {
            array = bd.Selecionar_Por_Data(format.format(data));
        } catch (SQLException ex) {
            Logger.getLogger(Todascontas.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultTableModel model = (DefaultTableModel) this.Tabela.getModel();
        model.setNumRows(0);
        for(int i = 0;i<array.size();i++){
            Conta contas = array.get(i);
            model.addRow(new Object[]{contas.getData(),contas.getDescricao(),contas.getValor()});
        }
        this.Tabela.setModel(model);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Dia_anterior = new javax.swing.JButton();
        Proximo_dia = new javax.swing.JButton();
        Fechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Abyssinica SIL", 0, 24)); // NOI18N
        setResizable(false);
        addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                formInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Descrição", "Valor"
            }
        ));
        jScrollPane1.setViewportView(Tabela);

        Dia_anterior.setText("Dia Anterior");
        Dia_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dia_anteriorActionPerformed(evt);
            }
        });

        Proximo_dia.setText("Próximo Dia");
        Proximo_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proximo_diaActionPerformed(evt);
            }
        });

        Fechar.setText("Fechar");
        Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Dia_anterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(Proximo_dia))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(Fechar)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Proximo_dia)
                    .addComponent(Dia_anterior)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fechar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_formInputMethodTextChanged
             // TODO add your handling code here:
    }//GEN-LAST:event_formInputMethodTextChanged
    
    private void Proximo_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proximo_diaActionPerformed
        calendar.add(Calendar.DAY_OF_MONTH, +1);        
        SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
        try {
            this.pegahoje(calendar.getTime());
        } catch (ParseException ex) {
            Logger.getLogger(Contashoje.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel1.setText(formatar.format(calendar.getTime())); // TODO add your handling code here:
    }//GEN-LAST:event_Proximo_diaActionPerformed

    private void Dia_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dia_anteriorActionPerformed
        calendar.add(Calendar.DAY_OF_MONTH, -1);        
        SimpleDateFormat formatar = new SimpleDateFormat("dd/MM/yyyy");
        try {
            this.pegahoje(calendar.getTime());
        } catch (ParseException ex) {
            Logger.getLogger(Contashoje.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel1.setText(formatar.format(calendar.getTime()));
        // TODO add your handling code here:
    }//GEN-LAST:event_Dia_anteriorActionPerformed

    private void FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_FecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Contashoje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Contashoje contas = new Contashoje();
                contas.setVisible(true);
                
                
                
                
            }
        });
       
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dia_anterior;
    private javax.swing.JButton Fechar;
    private javax.swing.JButton Proximo_dia;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
    
}
